#!/usr/bin/env bash

current_dir="$(
  cd "$(
    dirname "${BASH_SOURCE[0]}"
  )" &> /dev/null && pwd
)"

now=$(date +"%Y-%m-%d_%H:%M:%S")
path=""
dry=""
aws_access=${AWS_ACCESS_KEY_ID}
aws_secret=${AWS_SECRET_ACCESS_KEY}

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    path="$(realpath "$1")"
    echo "Resolved path: $path"
  fi
  shift
done

log () {
  if [[ $dry = "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute () {
  log "execute : $@"

  if [[ $dry = "1" ]]; then
    return
  fi

  "$@"
}

log "$aws_access"
log "$aws_secret"

execute "tar -czvf /tmp/$now.tar.gz \"$path\""
